export default `query HomePageQuery {
    carousels{
        id
        gallery{
            id
            url
            name
            alternativeText
            width
            height
            size
          }
        }
    products(limit: 6){
        id
        product_id
        Title
        Description
        gallery{
            id
            url
            }
        }
    hometexts{
        id
        firstText
        secondText
        }
    projects(limit: 6){
        id
        Title
        Description
        gallery{
            id
            url
        }
        }
}
`;
